#!/usr/bin/env python3
"""Convert the uncompressed AIFF-C emitted by macOS `say` to mono 8 kHz WAV.

This is a test-data helper, not a runtime audio decoder. It intentionally
supports only the narrow format generated by the documented test procedure.
"""

from __future__ import annotations

import argparse
import math
import struct
import wave
from pathlib import Path


def _extended_80_to_float(value: bytes) -> float:
    if len(value) != 10:
        raise ValueError("invalid AIFF sample-rate field")
    exponent = struct.unpack(">H", value[:2])[0]
    sign = -1 if exponent & 0x8000 else 1
    exponent &= 0x7FFF
    high, low = struct.unpack(">II", value[2:])
    if exponent == 0 and high == 0 and low == 0:
        return 0.0
    mantissa = (high << 32) | low
    return sign * mantissa * math.pow(2.0, exponent - 16383 - 63)


def read_say_aiff(path: Path) -> tuple[int, list[int]]:
    raw = path.read_bytes()
    if len(raw) < 12 or raw[:4] != b"FORM" or raw[8:12] not in {b"AIFF", b"AIFC"}:
        raise ValueError("input is not AIFF/AIFF-C")

    channels = sample_width = frame_count = None
    sample_rate: float | None = None
    compression: bytes | None = None
    samples_raw: bytes | None = None
    position = 12
    while position + 8 <= len(raw):
        chunk_id = raw[position : position + 4]
        chunk_size = struct.unpack(">I", raw[position + 4 : position + 8])[0]
        chunk_start = position + 8
        chunk_end = chunk_start + chunk_size
        if chunk_end > len(raw):
            raise ValueError(f"truncated AIFF chunk: {chunk_id!r}")
        chunk = raw[chunk_start:chunk_end]
        if chunk_id == b"COMM":
            if len(chunk) < 18:
                raise ValueError("invalid AIFF COMM chunk")
            channels, frame_count, sample_width = struct.unpack(">HIH", chunk[:8])
            sample_rate = _extended_80_to_float(chunk[8:18])
            compression = chunk[18:22] if len(chunk) >= 22 else b"NONE"
        elif chunk_id == b"SSND":
            if len(chunk) < 8:
                raise ValueError("invalid AIFF SSND chunk")
            offset, _block_size = struct.unpack(">II", chunk[:8])
            samples_raw = chunk[8 + offset :]
        position = chunk_end + (chunk_size % 2)

    if channels != 1:
        raise ValueError(f"test helper requires mono AIFF, got {channels!r} channels")
    if sample_width != 16:
        raise ValueError(f"test helper requires 16-bit AIFF, got {sample_width!r}")
    if compression not in {b"NONE", b"lpcm", b"twos"}:
        raise ValueError(f"unsupported AIFF compression: {compression!r}")
    if sample_rate is None or sample_rate <= 0 or samples_raw is None or frame_count is None:
        raise ValueError("AIFF is missing audio metadata or data")
    expected_bytes = frame_count * 2
    if len(samples_raw) < expected_bytes:
        raise ValueError("AIFF sample data is shorter than the declared frame count")
    samples = [value[0] for value in struct.iter_unpack(">h", samples_raw[:expected_bytes])]
    return round(sample_rate), samples


def resample_linear(samples: list[int], source_rate: int, target_rate: int = 8000) -> list[int]:
    if not samples:
        raise ValueError("cannot resample empty audio")
    target_count = max(1, round(len(samples) * target_rate / source_rate))
    result: list[int] = []
    for target_index in range(target_count):
        source_position = target_index * source_rate / target_rate
        left = min(int(source_position), len(samples) - 1)
        right = min(left + 1, len(samples) - 1)
        fraction = source_position - left
        value = round(samples[left] * (1.0 - fraction) + samples[right] * fraction)
        result.append(max(-32768, min(32767, value)))
    return result


def write_wav(path: Path, samples: list[int], sample_rate: int = 8000) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pcm = struct.pack(f"<{len(samples)}h", *samples)
    with wave.open(str(path), "wb") as output:
        output.setnchannels(1)
        output.setsampwidth(2)
        output.setframerate(sample_rate)
        output.writeframes(pcm)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    source_rate, samples = read_say_aiff(args.input)
    converted = resample_linear(samples, source_rate)
    write_wav(args.output, converted)
    print(
        f"created {args.output}: mono PCM16 8000 Hz, "
        f"duration={len(converted) / 8000:.3f}s"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
